# Generated by Django 5.0.4 on 2026-06-29 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

	dependencies = [
		('base', '0005_logentry_time_slot_workshop_location_and_more'),
	]

	operations = [
		migrations.CreateModel(
			name='RuntimeSetting',
			fields=[
				('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
				('key', models.CharField(max_length=64, unique=True)),
				('value', models.CharField(max_length=255)),
			],
		),
	]